/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author BoniBarBar
 */
public class home extends javax.swing.JFrame {
JLabel rum;
    /**
     * Creates new form home
     */
    public home() {
       
 initComponents();
        this.setLocationRelativeTo(this);
    }
public JButton getBtnAir() {
        return btnAir;
    }
    public JButton getBtnTangan() {
        return tangan;
    }
    public JButton getBtnTangan2() {
        return tangan2;
    }

    public JButton getBtntoko() {
        return Btntoko;
    }
    public JButton getBtnCangkul() {
       
        return btnCangkul;
    }
    public JButton getBtnGunting() {
        return btnGunting;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JButton getBtnPetak1() {
        return petak1;
    }

    public JButton getBtnPetak2() {
        return petak2;
    }

    public JButton getBtnPetak3() {
        return petak3;
    }

    public JButton getBtnPetak4() {
        return petak4;
    }

    public JButton getBtnPetak5() {
        return petak5;
    }

    public JButton getBtnPetak6() {
        return petak6;
    }

    
    public JLabel getLblObat() {
        return lblobat;
    }
    public JLabel getLblBibit() {
        return lblbibit;
    }

    public JLabel getLblPupuk() {
        return lblpupuk;
    }
    
    public JLabel getLblKoin() {
        return lblkoin;
    }

    public JLabel getLblAir5() {
        return air5;
    }

    public JLabel getLblAir4() {
        return air4;
    }

    public JLabel getLblAir3() {
        return air3;
 
    }

    public JLabel getLblAir2() {
        return air2;
    }

    public JLabel getLblAir1() {
        return air1;
    }

    public JLabel getLblAir() {
        return air;
    }
        public JLabel getLblTunas5() {
        return tunas5;
    }

    public JLabel getLblTunas4() {
        return tunas4;
    }

    public JLabel getLblTunas3() {
        return tunas3;
 
    }

    public JLabel getLblTunas2() {
        return tunas2;
    }

    public JLabel getLblTunas1() {
        return tunas1;
    }

    public JLabel getLblTunas() {
        return tunas;
    }
    

    public JLabel getLblPupuklbl1() {
        return pupuklbl1;
    }
    public JLabel getLblPupuklbl2() {
        return pupuklbl2;
    }
    public JLabel getLblPupuklbl3() {
        return pupuklbl3;
    }
    public JLabel getLblPupuklbl4() {
        return pupuklbl4;
    }
    public JLabel getLblPupuklbl5() {
        return pupuklbl5;
    }
    public JLabel getLblPupuklbl6() {
        return pupuklbl6;
    }
    
    
    public JLabel getLblObatlbl1() {
        return obatlbl1;
    }
    
    
    public JLabel getLblObatlbl2() {
        return obatlbl2;
    }
    
    
    public JLabel getLblObatlbl3() {
        return obatlbl3;
    }
    
    public JLabel getLblObatlbl4() {
        return obatlbl4;
    }
    
    
    public JLabel getLblObatlbl6() {
        return obatlbl6;
    }
    
    public JLabel getLblObatlbl5() {
        return obatlbl5;
    }
    
    
    public JLabel getLblGulma5() {
        return gulma5;
    }

    public JLabel getLblGulma4() {
        return gulma4;
    }

    public JLabel getLblGulma3() {
        return gulma3;
 
    }

    public JLabel getLblGulma2() {
        return gulma2;
    }

    public JLabel getLblGulma1() {
        return gulma1;
    }

    public JLabel getLblGulma() {
        return gulma;
    }
    
    public JLabel getLblusername() {
        return LblUsername;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        obatlbl1 = new javax.swing.JLabel();
        obatlbl2 = new javax.swing.JLabel();
        obatlbl3 = new javax.swing.JLabel();
        obatlbl4 = new javax.swing.JLabel();
        obatlbl5 = new javax.swing.JLabel();
        obatlbl6 = new javax.swing.JLabel();
        pupuklbl1 = new javax.swing.JLabel();
        pupuklbl2 = new javax.swing.JLabel();
        pupuklbl3 = new javax.swing.JLabel();
        pupuklbl4 = new javax.swing.JLabel();
        pupuklbl5 = new javax.swing.JLabel();
        pupuklbl6 = new javax.swing.JLabel();
        tunas = new javax.swing.JLabel();
        tunas2 = new javax.swing.JLabel();
        tunas3 = new javax.swing.JLabel();
        tunas4 = new javax.swing.JLabel();
        tunas5 = new javax.swing.JLabel();
        tunas1 = new javax.swing.JLabel();
        gulma2 = new javax.swing.JLabel();
        gulma3 = new javax.swing.JLabel();
        gulma1 = new javax.swing.JLabel();
        gulma4 = new javax.swing.JLabel();
        gulma5 = new javax.swing.JLabel();
        gulma = new javax.swing.JLabel();
        lblbibit = new javax.swing.JLabel();
        petak6 = new javax.swing.JButton();
        petak1 = new javax.swing.JButton();
        petak2 = new javax.swing.JButton();
        petak5 = new javax.swing.JButton();
        petak4 = new javax.swing.JButton();
        petak3 = new javax.swing.JButton();
        lblpupuk = new javax.swing.JLabel();
        lblobat = new javax.swing.JLabel();
        btnGunting = new javax.swing.JButton();
        btnCangkul = new javax.swing.JButton();
        btnAir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        air = new javax.swing.JLabel();
        air1 = new javax.swing.JLabel();
        air2 = new javax.swing.JLabel();
        air3 = new javax.swing.JLabel();
        air4 = new javax.swing.JLabel();
        air5 = new javax.swing.JLabel();
        lblkoin = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        LblUsername = new javax.swing.JLabel();
        Btntoko = new javax.swing.JButton();
        tangan = new javax.swing.JButton();
        tangan2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        obatlbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Uler.png"))); // NOI18N
        getContentPane().add(obatlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        obatlbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Uler.png"))); // NOI18N
        getContentPane().add(obatlbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        obatlbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Uler.png"))); // NOI18N
        getContentPane().add(obatlbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        obatlbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Uler.png"))); // NOI18N
        getContentPane().add(obatlbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        obatlbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Uler.png"))); // NOI18N
        getContentPane().add(obatlbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        obatlbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Uler.png"))); // NOI18N
        getContentPane().add(obatlbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        pupuklbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 3/Pisah/Pupuk Notif.png"))); // NOI18N
        getContentPane().add(pupuklbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 80, 60));

        pupuklbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 3/Pisah/Pupuk Notif.png"))); // NOI18N
        getContentPane().add(pupuklbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        pupuklbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 3/Pisah/Pupuk Notif.png"))); // NOI18N
        getContentPane().add(pupuklbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        pupuklbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 3/Pisah/Pupuk Notif.png"))); // NOI18N
        getContentPane().add(pupuklbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, -1));

        pupuklbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 3/Pisah/Pupuk Notif.png"))); // NOI18N
        getContentPane().add(pupuklbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        pupuklbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 3/Pisah/Pupuk Notif.png"))); // NOI18N
        getContentPane().add(pupuklbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        tunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Tunas.png"))); // NOI18N
        getContentPane().add(tunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        tunas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Tunas.png"))); // NOI18N
        getContentPane().add(tunas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, -1));

        tunas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Tunas.png"))); // NOI18N
        getContentPane().add(tunas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));

        tunas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Tunas.png"))); // NOI18N
        getContentPane().add(tunas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        tunas5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Tunas.png"))); // NOI18N
        getContentPane().add(tunas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        tunas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Tunas.png"))); // NOI18N
        getContentPane().add(tunas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        gulma2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Gulma.png"))); // NOI18N
        getContentPane().add(gulma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 130, 160));

        gulma3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Gulma.png"))); // NOI18N
        getContentPane().add(gulma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        gulma1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Gulma.png"))); // NOI18N
        getContentPane().add(gulma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        gulma4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Gulma.png"))); // NOI18N
        getContentPane().add(gulma4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        gulma5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Gulma.png"))); // NOI18N
        getContentPane().add(gulma5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        gulma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Gulma.png"))); // NOI18N
        getContentPane().add(gulma, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        lblbibit.setFont(new java.awt.Font("Roboto Bk", 0, 16)); // NOI18N
        getContentPane().add(lblbibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 40, 20));

        petak6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GundukanBaru.png"))); // NOI18N
        petak6.setBorderPainted(false);
        petak6.setContentAreaFilled(false);
        petak6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petak6ActionPerformed(evt);
            }
        });
        getContentPane().add(petak6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 90, -1));

        petak1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GundukanBaru.png"))); // NOI18N
        petak1.setBorderPainted(false);
        petak1.setContentAreaFilled(false);
        petak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petak1ActionPerformed(evt);
            }
        });
        getContentPane().add(petak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 80, -1));

        petak2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GundukanBaru.png"))); // NOI18N
        petak2.setBorderPainted(false);
        petak2.setContentAreaFilled(false);
        petak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petak2ActionPerformed(evt);
            }
        });
        getContentPane().add(petak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 70, -1));

        petak5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GundukanBaru.png"))); // NOI18N
        petak5.setBorderPainted(false);
        petak5.setContentAreaFilled(false);
        petak5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petak5ActionPerformed(evt);
            }
        });
        getContentPane().add(petak5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 80, -1));

        petak4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GundukanBaru.png"))); // NOI18N
        petak4.setBorderPainted(false);
        petak4.setContentAreaFilled(false);
        petak4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petak4ActionPerformed(evt);
            }
        });
        getContentPane().add(petak4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 80, -1));

        petak3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GundukanBaru.png"))); // NOI18N
        petak3.setBorderPainted(false);
        petak3.setContentAreaFilled(false);
        petak3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petak3ActionPerformed(evt);
            }
        });
        getContentPane().add(petak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 80, -1));

        lblpupuk.setFont(new java.awt.Font("Roboto Bk", 0, 16)); // NOI18N
        getContentPane().add(lblpupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 40, 20));

        lblobat.setFont(new java.awt.Font("Roboto Bk", 0, 16)); // NOI18N
        getContentPane().add(lblobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 30, 20));

        btnGunting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/inventory/Gunting.png"))); // NOI18N
        btnGunting.setBorderPainted(false);
        btnGunting.setContentAreaFilled(false);
        btnGunting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuntingActionPerformed(evt);
            }
        });
        getContentPane().add(btnGunting, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        btnCangkul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/inventory/Cangkul.png"))); // NOI18N
        btnCangkul.setBorderPainted(false);
        btnCangkul.setContentAreaFilled(false);
        btnCangkul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCangkul.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Highlight Cangkul.png"))); // NOI18N
        btnCangkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCangkulActionPerformed(evt);
            }
        });
        getContentPane().add(btnCangkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, -1, -1));

        btnAir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/inventory/Siram.png"))); // NOI18N
        btnAir.setBorderPainted(false);
        btnAir.setContentAreaFilled(false);
        btnAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        air.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Ngelak.png"))); // NOI18N
        getContentPane().add(air, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        air1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Ngelak.png"))); // NOI18N
        getContentPane().add(air1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        air2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Ngelak.png"))); // NOI18N
        getContentPane().add(air2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, -1, -1));

        air3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Ngelak.png"))); // NOI18N
        getContentPane().add(air3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, -1));

        air4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Ngelak.png"))); // NOI18N
        getContentPane().add(air4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        air5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Ngelak.png"))); // NOI18N
        getContentPane().add(air5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        lblkoin.setFont(new java.awt.Font("Roboto Bk", 0, 16)); // NOI18N
        getContentPane().add(lblkoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 60, 30));

        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 40));

        LblUsername.setFont(new java.awt.Font("Roboto Bk", 0, 16)); // NOI18N
        getContentPane().add(LblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, 30));

        Btntoko.setBorderPainted(false);
        Btntoko.setContentAreaFilled(false);
        Btntoko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtntokoActionPerformed(evt);
            }
        });
        getContentPane().add(Btntoko, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 50, 50));

        tangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 2/Pisah/tangan.png"))); // NOI18N
        tangan.setBorderPainted(false);
        tangan.setContentAreaFilled(false);
        getContentPane().add(tangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 60, 60));

        tangan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 2/Pisah/tangan.png"))); // NOI18N
        tangan2.setBorderPainted(false);
        tangan2.setContentAreaFilled(false);
        getContentPane().add(tangan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Lahan Bersih.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 970, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuntingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuntingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuntingActionPerformed

    private void btnCangkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCangkulActionPerformed
        
    }//GEN-LAST:event_btnCangkulActionPerformed

    private void btnAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAirActionPerformed

    private void petak4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petak4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petak4ActionPerformed

    private void petak3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petak3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petak3ActionPerformed

    private void petak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petak1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petak1ActionPerformed

    private void petak6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petak6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petak6ActionPerformed

    private void petak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petak2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petak2ActionPerformed

    private void petak5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petak5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petak5ActionPerformed

    private void BtntokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtntokoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtntokoActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btntoko;
    private javax.swing.JLabel LblUsername;
    private javax.swing.JLabel air;
    private javax.swing.JLabel air1;
    private javax.swing.JLabel air2;
    private javax.swing.JLabel air3;
    private javax.swing.JLabel air4;
    private javax.swing.JLabel air5;
    private javax.swing.JButton btnAir;
    private javax.swing.JButton btnCangkul;
    private javax.swing.JButton btnGunting;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel gulma;
    private javax.swing.JLabel gulma1;
    private javax.swing.JLabel gulma2;
    private javax.swing.JLabel gulma3;
    private javax.swing.JLabel gulma4;
    private javax.swing.JLabel gulma5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblbibit;
    private javax.swing.JLabel lblkoin;
    private javax.swing.JLabel lblobat;
    private javax.swing.JLabel lblpupuk;
    private javax.swing.JLabel obatlbl1;
    private javax.swing.JLabel obatlbl2;
    private javax.swing.JLabel obatlbl3;
    private javax.swing.JLabel obatlbl4;
    private javax.swing.JLabel obatlbl5;
    private javax.swing.JLabel obatlbl6;
    private javax.swing.JButton petak1;
    private javax.swing.JButton petak2;
    private javax.swing.JButton petak3;
    private javax.swing.JButton petak4;
    private javax.swing.JButton petak5;
    private javax.swing.JButton petak6;
    private javax.swing.JLabel pupuklbl1;
    private javax.swing.JLabel pupuklbl2;
    private javax.swing.JLabel pupuklbl3;
    private javax.swing.JLabel pupuklbl4;
    private javax.swing.JLabel pupuklbl5;
    private javax.swing.JLabel pupuklbl6;
    private javax.swing.JButton tangan;
    private javax.swing.JButton tangan2;
    private javax.swing.JLabel tunas;
    private javax.swing.JLabel tunas1;
    private javax.swing.JLabel tunas2;
    private javax.swing.JLabel tunas3;
    private javax.swing.JLabel tunas4;
    private javax.swing.JLabel tunas5;
    // End of variables declaration//GEN-END:variables
}
