/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author BoniBarBar
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }
    
 public JButton getBtntoko() {
        return toko;
    }

    public JButton getBtnkeranjang() {
        return keranjang;
    }

    public JButton getBtngunting() {
        return gunting;
    }

    public JButton getBtnpenyiram() {
        return penyiram;
    }
 public JLabel getLblBibit() {
        return jmlbibit;
    }
    public JButton getBtnkeluar() {
        return keluar;
    }
    
 
    public JLabel getLabelUsername() {
        return username;
    }
 public JButton getBtnKotak1() {
        return petak1;
    }

  public JButton getBtnKotak2() {
        return petak2;
    }
   public JButton getBtnKotak3() {
        return petak3;
    }
    public JButton getBtnKotak4() {
        return petak4;
    }
     public JButton getBtnKotak5() {
        return petak5;
    }
      public JButton getBtnKotak6() {
        return petak6;
    }
  public JLabel getLblAir1() {
        return air1;
    }

    public JLabel getLblAir2() {
        return air2;
    }

    public JLabel getLblAir3() {
        return air3;
    }

    public JLabel getLblAir4() {
        return air4;
    }

    public JLabel getLblAir5() {
        return air5;
    }

    public JLabel getLblAir6() {
        return air6;
    }

    
    



  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toko = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        penyiram = new javax.swing.JButton();
        gunting = new javax.swing.JButton();
        jmlbibit = new javax.swing.JLabel();
        jmlpupuk = new javax.swing.JLabel();
        jmlpoin = new javax.swing.JLabel();
        keranjang = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        petak1 = new javax.swing.JButton();
        petak2 = new javax.swing.JButton();
        petak3 = new javax.swing.JButton();
        petak4 = new javax.swing.JButton();
        petak5 = new javax.swing.JButton();
        petak6 = new javax.swing.JButton();
        air1 = new javax.swing.JLabel();
        air2 = new javax.swing.JLabel();
        air3 = new javax.swing.JLabel();
        air4 = new javax.swing.JLabel();
        air6 = new javax.swing.JLabel();
        air5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toko.setText("toko");
        toko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokoActionPerformed(evt);
            }
        });
        getContentPane().add(toko, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 60, 50));

        username.setText("Nama player");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 410, 130, 40));

        penyiram.setText("Penyiram");
        penyiram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penyiramActionPerformed(evt);
            }
        });
        getContentPane().add(penyiram, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 80, 60));

        gunting.setText("gunting");
        gunting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guntingActionPerformed(evt);
            }
        });
        getContentPane().add(gunting, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 80, 60));

        jmlbibit.setText("jmlbibit");
        getContentPane().add(jmlbibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 70, 40));

        jmlpupuk.setText("jmlpupuk");
        getContentPane().add(jmlpupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jmlpoin.setText("jmlpoin");
        getContentPane().add(jmlpoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        keranjang.setText("keranjang");
        keranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keranjangActionPerformed(evt);
            }
        });
        getContentPane().add(keranjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 80, 50));

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 80, 30));

        petak1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tanah kosong.png"))); // NOI18N
        petak1.setText("jButton1");
        getContentPane().add(petak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 80, 50));

        petak2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tanah kosong.png"))); // NOI18N
        petak2.setText("jButton2");
        getContentPane().add(petak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 443, 90, 50));

        petak3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tanah kosong.png"))); // NOI18N
        petak3.setText("jButton3");
        getContentPane().add(petak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 443, 90, 50));

        petak4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tanah kosong.png"))); // NOI18N
        petak4.setText("jButton4");
        getContentPane().add(petak4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 273, 90, 50));

        petak5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tanah kosong.png"))); // NOI18N
        petak5.setText("jButton5");
        getContentPane().add(petak5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 90, 50));

        petak6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tanah kosong.png"))); // NOI18N
        petak6.setText("jButton6");
        getContentPane().add(petak6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 80, 50));

        air1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/notif air.png"))); // NOI18N
        getContentPane().add(air1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 60, 60));

        air2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/notif air.png"))); // NOI18N
        getContentPane().add(air2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        air3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/notif air.png"))); // NOI18N
        getContentPane().add(air3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 70, 70));

        air4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/notif air.png"))); // NOI18N
        getContentPane().add(air4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 374, 70, 60));

        air6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/notif air.png"))); // NOI18N
        getContentPane().add(air6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 184, 60, 70));

        air5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/notif air.png"))); // NOI18N
        getContentPane().add(air5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 374, 60, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Lahan.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tokoActionPerformed

    private void keranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keranjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keranjangActionPerformed

    private void guntingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guntingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guntingActionPerformed

    private void penyiramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penyiramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penyiramActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel air1;
    private javax.swing.JLabel air2;
    private javax.swing.JLabel air3;
    private javax.swing.JLabel air4;
    private javax.swing.JLabel air5;
    private javax.swing.JLabel air6;
    private javax.swing.JButton gunting;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jmlbibit;
    private javax.swing.JLabel jmlpoin;
    private javax.swing.JLabel jmlpupuk;
    private javax.swing.JButton keluar;
    private javax.swing.JButton keranjang;
    private javax.swing.JButton penyiram;
    private javax.swing.JButton petak1;
    private javax.swing.JButton petak2;
    private javax.swing.JButton petak3;
    private javax.swing.JButton petak4;
    private javax.swing.JButton petak5;
    private javax.swing.JButton petak6;
    private javax.swing.JButton toko;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables


  
}
