/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.UnsupportedAudioFileException;
import sun.audio.*;
public class MainMenu extends javax.swing.JFrame {

    
    public MainMenu()throws InterruptedException {
        initComponents();
        this.setLocationRelativeTo(this);
//        usernameFrame.setLocationRelativeTo(this);
//        usernameFrame.setExtendedState(usernameFrame.getExtendedState()| usernameFrame.MAXIMIZED_BOTH);
        usernameFrame.setSize(800,600);
    }
    public JButton getBtnAbout() {
        return tentangB;
    }
    public JButton getBtnLoad() {
        return Load;
    }
    public JButton getBtnKeluar() {
        return keluarB;
    }
    public JButton getBtnMulai() {
        return mainB;
    }
    public JButton getBtnBatal() {
        return btnBatal;
    }
     public void klikvol(ActionListener a) {
        vol.addActionListener(a);
    }
    public JButton getBtnOk() {
        return btnOk;
    }
    public JTextField getFieldUsername() {
        return fieldUsername;
    }
    public void tampilPesan(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    public JFrame getUsernameFrame() {
        return usernameFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameFrame = new javax.swing.JFrame();
        fieldUsername = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainB = new javax.swing.JButton();
        tentangB = new javax.swing.JButton();
        keluarB = new javax.swing.JButton();
        Load = new javax.swing.JButton();
        vol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        usernameFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        usernameFrame.setMaximumSize(new java.awt.Dimension(800, 630));
        usernameFrame.setPreferredSize(new java.awt.Dimension(800, 630));
        usernameFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldUsername.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fieldUsername.setBorder(null);
        fieldUsername.setOpaque(false);
        fieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldUsernameKeyTyped(evt);
            }
        });
        usernameFrame.getContentPane().add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 220, 40));

        btnBatal.setBorderPainted(false);
        btnBatal.setContentAreaFilled(false);
        usernameFrame.getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 50, 30));

        btnOk.setBorderPainted(false);
        btnOk.setContentAreaFilled(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        usernameFrame.getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 60, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Menu/GameBaru.png"))); // NOI18N
        usernameFrame.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 520, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Menu/HomeBlur.png"))); // NOI18N
        usernameFrame.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 810, 600));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainB.setBorderPainted(false);
        mainB.setContentAreaFilled(false);
        mainB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBActionPerformed(evt);
            }
        });
        getContentPane().add(mainB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 210, 60));

        tentangB.setBorderPainted(false);
        tentangB.setContentAreaFilled(false);
        tentangB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tentangB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentangBActionPerformed(evt);
            }
        });
        getContentPane().add(tentangB, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 60, 60));

        keluarB.setBorderPainted(false);
        keluarB.setContentAreaFilled(false);
        keluarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarBActionPerformed(evt);
            }
        });
        getContentPane().add(keluarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 120, 50));

        Load.setBorderPainted(false);
        Load.setContentAreaFilled(false);
        Load.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Load, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 180, 70));

        vol.setBorderPainted(false);
        vol.setContentAreaFilled(false);
        vol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volActionPerformed(evt);
            }
        });
        getContentPane().add(vol, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 523, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Menu/Home.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 800, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tentangBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tentangBActionPerformed

    private void mainBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBActionPerformed
 dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_mainBActionPerformed

    private void keluarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarBActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_keluarBActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    private void volActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volActionPerformed

    private void fieldUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldUsernameKeyTyped
if(fieldUsername.getText().length()>5){
    JOptionPane.showMessageDialog(null,"username tidak boleh melebihi 5 huruf !");
    evt.consume();
}
    }//GEN-LAST:event_fieldUsernameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainMenu().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Load;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOk;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton keluarB;
    private javax.swing.JButton mainB;
    private javax.swing.JButton tentangB;
    private javax.swing.JFrame usernameFrame;
    public javax.swing.JButton vol;
    // End of variables declaration//GEN-END:variables

}
