/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class MainMenu extends javax.swing.JFrame {

    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(this);
        usernameFrame.setLocationRelativeTo(this);

    }
    
    
    public JButton getBtnAbout() {
        return tentangB;
    }

    public JButton getBtnLoad() {
        return Load;
    }

    public JButton getBtnKeluar() {
        return keluarB;
    }

    public JButton getBtnMulai() {
        return mainB;
    }

    public JButton getBtnPetunjuk() {
        return petunjukB;
    }

    public JButton getBtnBatal() {
        return btnBatal;
    }

    public JButton getBtnOk() {
        return btnOk;
    }

    public JTextField getFieldUsername() {
        return fieldUsername;
    }

    public void tampilPesan(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    public JFrame getUsernameFrame() {
        return usernameFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameFrame = new javax.swing.JFrame();
        fieldUsername = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        mainB = new javax.swing.JButton();
        petunjukB = new javax.swing.JButton();
        tentangB = new javax.swing.JButton();
        keluarB = new javax.swing.JButton();
        Load = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        usernameFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldUsername.setText("jTextField1");
        usernameFrame.getContentPane().add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 370, 90));

        btnBatal.setText("jButton1");
        usernameFrame.getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        btnOk.setText("jButton1");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        usernameFrame.getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 120, 70));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainB.setText("Permainan Baru");
        mainB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBActionPerformed(evt);
            }
        });
        getContentPane().add(mainB, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 160, 60));

        petunjukB.setText("Petunjuk");
        petunjukB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petunjukBActionPerformed(evt);
            }
        });
        getContentPane().add(petunjukB, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 260, 170, 40));

        tentangB.setText("Tentang");
        tentangB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentangBActionPerformed(evt);
            }
        });
        getContentPane().add(tentangB, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 323, 170, 50));

        keluarB.setText("Keluar");
        keluarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarBActionPerformed(evt);
            }
        });
        getContentPane().add(keluarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, 180, 50));

        Load.setText("Lanjutkan");
        getContentPane().add(Load, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 173, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Home.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 800, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void petunjukBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petunjukBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petunjukBActionPerformed

    private void tentangBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tentangBActionPerformed

    private void mainBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainBActionPerformed

    private void keluarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarBActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_keluarBActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Load;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOk;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton keluarB;
    private javax.swing.JButton mainB;
    private javax.swing.JButton petunjukB;
    private javax.swing.JButton tentangB;
    private javax.swing.JFrame usernameFrame;
    // End of variables declaration//GEN-END:variables

}
