/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;

public class toko extends javax.swing.JFrame {

    public toko() {
        initComponents();
        this.setLocationRelativeTo(this);

    }

    public JButton getBtnItem1() {
        return btnItem1;
    }

    public JButton getBtnItem2() {
        return btnItem2;
    }

    public JButton getBtnItem3() {
        return btnItem3;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JLabel getLblKoin() {
        return lblKoin;
    }

    public JLabel getLblBibit() {
        return lblBibit;
    }

    public JLabel getLblPupuk() {
        return lblPupuk;
    }

    public JLabel getLblObat() {
        return lblObat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnItem1 = new javax.swing.JButton();
        btnItem2 = new javax.swing.JButton();
        btnItem3 = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        lblKoin = new javax.swing.JLabel();
        lblBibit = new javax.swing.JLabel();
        lblPupuk = new javax.swing.JLabel();
        lblObat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 2/Pisah/Bibit.png"))); // NOI18N
        btnItem1.setBorderPainted(false);
        btnItem1.setContentAreaFilled(false);
        btnItem1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan/Bibit Highlight.png"))); // NOI18N
        btnItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItem1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 110, 160));

        btnItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 2/Pisah/Pupuk.png"))); // NOI18N
        btnItem2.setBorderPainted(false);
        btnItem2.setContentAreaFilled(false);
        btnItem2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 2/Pisah/Pupuk Highlight.png"))); // NOI18N
        btnItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItem2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 110, 170));

        btnItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 2/Pisah/Pestisida.png"))); // NOI18N
        btnItem3.setBorderPainted(false);
        btnItem3.setContentAreaFilled(false);
        btnItem3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sprint 2/Pisah/Pesisida Highlight.png"))); // NOI18N
        getContentPane().add(btnItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 130, 170));

        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 40, 40));

        lblKoin.setFont(new java.awt.Font("Roboto Bk", 0, 11)); // NOI18N
        getContentPane().add(lblKoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 50, 30));

        lblBibit.setFont(new java.awt.Font("Roboto Bk", 0, 11)); // NOI18N
        getContentPane().add(lblBibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 70, 30));

        lblPupuk.setFont(new java.awt.Font("Roboto Bk", 0, 11)); // NOI18N
        getContentPane().add(lblPupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 70, 30));

        lblObat.setFont(new java.awt.Font("Roboto Bk", 0, 11)); // NOI18N
        getContentPane().add(lblObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/toko/yo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnItem1ActionPerformed

    private void btnItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new toko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnItem1;
    private javax.swing.JButton btnItem2;
    private javax.swing.JButton btnItem3;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBibit;
    private javax.swing.JLabel lblKoin;
    private javax.swing.JLabel lblObat;
    private javax.swing.JLabel lblPupuk;
    // End of variables declaration//GEN-END:variables
}
